server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: 
    - application-mariadb.yml
  application:
    name: emp-spring-local
  data:
    rest: 
       base-path: "/"
