server:
  port: 8080
  servlet:
    context-path: /emp-spring

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  config:
    import: 
    - application-mariadb.yml
  application:
    name: emp-spring-local
  data:
    rest: 
       base-path: "/api"

logging:
  level:
    '[com.htdp1.empspring]': debug
